echo Cloning backend...
git clone https://github.com/Shahaf11111/StoreMaven.git --single-branch --branch backend backend
echo Cloning frontend...
git clone https://github.com/Shahaf11111/StoreMaven.git --single-branch --branch frontend frontend
echo Installing backend...
cd backend && npm install && cd ..
echo Installing frontend...
cd frontend && npm install && cd ..
echo Done!
